import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Authcontext from "@/context/AuthContext";
import SWRConfigContext from "@/context/SWRConfigContext";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body className='w-full max-w-screen-xl mx-auto overflow-auto bg-neutral-50'>
        <SWRConfigContext>
          <Authcontext>
            <header className="sticy top-0 bg-white z-10 border-b"><Navbar /></header>
            <main>
              {children}
            </main>
          </Authcontext>
        </SWRConfigContext>
      </body>
    </html >
  );
}
